import type { ReferenceObject } from "./types";

/**
 * Seed reference dataset — must stay in sync with REFERENCE_DATA.md, which is the
 * source of truth. Do not add/edit entries here without updating that file first.
 */
export const REFERENCES: ReferenceObject[] = [
  { id: "credit_card", name: "credit card", pluralName: "credit cards", category: "standardized", canonicalLength: 0.0856, variability: "low", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "ISO/IEC 7810 ID-1 card, 85.60mm" },
  { id: "smartphone", name: "smartphone", pluralName: "smartphones", category: "everyday", canonicalLength: 0.150, variability: "medium", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "typical modern phone length (~5.5-6.5in)" },
  { id: "letter_paper", name: "sheet of paper", pluralName: "sheets of paper", category: "standardized", canonicalLength: 0.2794, variability: "low", familiarity: 0.80, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "US Letter 11in long edge (A4 close: 297mm)" },
  { id: "adult_hand", name: "adult hand", pluralName: "adult hands", category: "embodied", canonicalLength: 0.18, variability: "medium", familiarity: 0.70, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "wrist-to-fingertip, anthropometric average" },
  { id: "adult_foot", name: "adult foot", pluralName: "adult feet", category: "embodied", canonicalLength: 0.26, variability: "medium", familiarity: 0.60, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "average adult foot length" },
  { id: "door_width", name: "door width", pluralName: "door widths", category: "standardized", canonicalLength: 0.86, variability: "medium", familiarity: 0.75, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "typical interior/exterior door, 32-36in" },
  { id: "arm_reach", name: "arm's reach", pluralName: "arm's reaches", category: "embodied", canonicalLength: 0.65, variability: "medium", familiarity: 0.55, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "average forearm+hand reach segment" },
  { id: "adult_height", name: "adult height", pluralName: "adult heights", category: "embodied", canonicalLength: 1.70, variability: "medium", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "global average adult height (varies by region/sex)" },
  { id: "door_height", name: "door height", pluralName: "door heights", category: "standardized", canonicalLength: 2.03, variability: "low", familiarity: 0.70, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "standard residential door height, 80in" },
  { id: "queen_bed", name: "queen bed", pluralName: "queen beds", category: "everyday", canonicalLength: 2.03, variability: "low", familiarity: 0.65, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "industry-standard queen mattress, 80in" },
  { id: "walking_step", name: "step", pluralName: "steps", category: "embodied", canonicalLength: 0.75, variability: "high", familiarity: 0.75, minUsefulRatio: 0.3, maxUsefulRatio: 150, countable: true, source: "average adult stride length (~2.5ft; varies by height/sex)" },
  { id: "parking_space", name: "parking space", pluralName: "parking spaces", category: "standardized", canonicalLength: 5.50, variability: "medium", familiarity: 0.60, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "typical US stall length, 18ft" },
  { id: "sedan", name: "car length", pluralName: "car lengths", category: "vehicle", canonicalLength: 4.50, variability: "medium", familiarity: 0.90, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "average compact/mid-size sedan" },
  { id: "suv", name: "SUV length", pluralName: "SUV lengths", category: "vehicle", canonicalLength: 4.90, variability: "medium", familiarity: 0.75, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "average SUV" },
  { id: "shipping_container", name: "shipping container", pluralName: "shipping containers", category: "standardized", canonicalLength: 6.10, variability: "low", familiarity: 0.40, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "ISO 668 20ft container, 19'10.5\"" },
  { id: "school_bus", name: "school bus", pluralName: "school buses", category: "vehicle", canonicalLength: 12.2, variability: "medium", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, locale: "US", source: "typical US school bus, ~40ft" },
  { id: "semi_truck", name: "semi-truck length", pluralName: "semi-truck lengths", category: "vehicle", canonicalLength: 22.0, variability: "medium", familiarity: 0.55, minUsefulRatio: 0.3, maxUsefulRatio: 10, locale: "US", source: "tractor + 53ft trailer, legal length varies by state" },
  { id: "bowling_lane", name: "bowling lane", pluralName: "bowling lanes", category: "standardized", canonicalLength: 18.29, variability: "low", familiarity: 0.35, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "USBC/WTBA regulation, foul line to head pin, 60ft" },
  { id: "volleyball_court", name: "volleyball court", pluralName: "volleyball courts", category: "standardized", canonicalLength: 18.0, variability: "low", familiarity: 0.40, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "FIVB regulation" },
  { id: "tennis_court", name: "tennis court", pluralName: "tennis courts", category: "standardized", canonicalLength: 23.77, variability: "low", familiarity: 0.55, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "ITF regulation, 78ft" },
  { id: "basketball_court_fiba", name: "basketball court (international)", pluralName: "basketball courts (international)", category: "standardized", canonicalLength: 28.0, variability: "low", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "FIBA regulation" },
  { id: "basketball_court_nba", name: "basketball court (NBA)", pluralName: "basketball courts (NBA)", category: "standardized", canonicalLength: 28.65, variability: "low", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, locale: "US", source: "NBA regulation, 94ft" },
  { id: "olympic_pool", name: "Olympic swimming pool", pluralName: "Olympic swimming pools", category: "standardized", canonicalLength: 50.0, variability: "low", familiarity: 0.60, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "FINA long-course regulation" },
  { id: "soccer_pitch", name: "soccer pitch", pluralName: "soccer pitches", category: "standardized", canonicalLength: 105.0, variability: "medium", familiarity: 0.85, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "FIFA-recommended for international matches; 100-110m allowed" },
  { id: "football_field", name: "football field", pluralName: "football fields", category: "standardized", canonicalLength: 109.7, variability: "low", familiarity: 0.75, minUsefulRatio: 0.3, maxUsefulRatio: 10, locale: "US", source: "NFL/NCAA, includes end zones, 120yd" },
  { id: "city_block", name: "city block", pluralName: "city blocks", category: "landmark", canonicalLength: 100.0, variability: "high", familiarity: 0.70, minUsefulRatio: 0.3, maxUsefulRatio: 10, source: "rough global typical - varies enormously by city" },
  { id: "walking_minute", name: "minute of walking", pluralName: "minutes of walking", category: "embodied", canonicalLength: 80.0, variability: "high", familiarity: 0.60, minUsefulRatio: 0.3, maxUsefulRatio: 60, countable: true, source: "~5km/h average walking pace" },
];
